### DISCUSSION TITLE
calculation power consumption with home assistant

### DISCUSSION THREAD

**Discussion by ap20132022** [raomin/ESPAltherma#246] [Q&A]
Dear guys,
I want to calculate the electrical power consumption and show it with home assistant.
I use this syntax:
     - name: "PowerConsumption"
        unit_of_measurement: 'W'
        state: "{% if is_state_attr('sensor.althermasensors','Operation Mode', 'Heating') and is_state_attr('sensor.althermasensors','Freeze Protection', 'OFF')  %} 
{{ 
  (state_attr('sensor.althermasensors','INV primary current (A)') | float * state_attr('sensor.althermasensors','Voltage (N-phase) (V)')|float / 1000))
  |round(2)
}}
{% else %} 0 {%endif%}"

But it doesn't work.
Do you have any ideas?
Thanks a lot.

**Comment by tarmor1** [comment]
To be truly honest, it's hard to help unless knowing what does it currently output and all that.
Let me share you my example. As you can see, I'm using the Voltage from Phase 2 that is given by my Solar Inverter Smart Meter (And in case that is Unavailable, it reverts to default 230V.  (My unit is on Ph2)

```
      - name: "Daikin Altherma Total Power"
        state: >
          {%- set extras = 0 -%}
          {%- set voltage = 230 -%}
          {%- if states('sensor.power_meter_phase_b_voltage') != "unavailable" %}
            {%- set voltage = states('sensor.power_meter_phase_b_voltage') -%}
          {%- endif %}
          {%- if states('binary_sensor.booster_heater') == "on" %}
            {%- set extras = extras + 2000 %}
          {%- endif %}
          {%- if states('binary_sensor.buh_step1') == "on" %}
            {%- set extras = extras + 3000 %}
          {%- endif %}
          {%- if states('binary_sensor.buh_step2') == "on" %}
            {%- set extras = extras + 6000 %}
          {%- endif -%}
          {{ extras + (voltage|float * state_attr('sensor.althermasensors','INV primary current (A)')|float)|round(0) }}
        device_class: power
        unit_of_measurement: "W"
        state_class: measurement

```

As you can see, I'm doing the same - multiply U*I to get P.

And as well, as I have booster heater for domestic water, I'll add those +2000W once I see them to be active.
The same goes for BUH Step 1 and BUH Step 2.
As well I see you are using W as unit but dividing by 1000 to get kW?
I recommend having W as default value, with that you can build with Riemann-Sum integrator in HA as well kWh units and calculate consumption over time, have Utility Meter etc.

As well would be good if anybody more knowledgeable would be able to answer if:
* Is it correct to use INV Primary current? I remember seeing somewhere here a good explanation between INV Primary and INV Secondary but can't find it now...

**Comment by mx-vatte** [comment]
@ap20132022 I calculate the COP while heating as followed:
```
espaltherma_cop_heizen:
        friendly_name: "COP Heizen"
        unit_of_measurement: 'COP'
        value_template: "{% if is_state_attr('sensor.althermasensors','I/U betriebsart', 'Heating') and is_state_attr('sensor.althermasensors','Abtauung', 'OFF') and state_attr('sensor.althermasensors','INV Primärstrom (A)')  | float != 0  %} 
{{ 
  (((state_attr('sensor.althermasensors','Durchflussmenge (l/min)')| float * 0.06 * 1.16 * (state_attr('sensor.althermasensors','R1T-Wasser Vorlauftemp. nach dem Plattenwärmetauscher') | float - state_attr('sensor.althermasensors','R4T-Wasser Rücklauftemp. vor dem Plattenwärmetauscher')|float) )
    /
  (state_attr('sensor.althermasensors','INV Primärstrom (A)') | float * (233 * 3) | float / 1000 )))
  | round(2)
}}
{% else %} 0 {%endif%}"
```

and the electrical power consumption as followed:
```
espaltherma_leistung_elektrisch:
        friendly_name: "Leistung Elektrisch"
        value_template: "{{ ( state_attr('sensor.althermasensors','INV Primärstrom (A)')  | float * 0.233 * 3 ) | round(3) }}"
        unit_of_measurement: 'kW'
```

@tarmor1 I would like to calculate the amount of total power also. I struggle with creating binary sensors from the espaltherma mqtt message in HomeAssistant. Could you please post the code how you have done this?

My created sensors keep the state unknown.

Thx in advance,
Patrick

**Reply by tarmor1** [reply]
> @tarmor1 I would like to calculate the amount of total power also. I struggle with creating binary sensors from the espaltherma mqtt message in HomeAssistant. Could you please post the code how you have done this?
> 
> My created sensors keep the state unknown.
> 
> Thx in advance, Patrick

This is how I have it:
```
  ######## BINARY ONES START HERE
  - binary_sensor:
      - name: "Defrost Operation"
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'Defrost Operation') }}
      - name: "3way valve(On:DHW_Off:Space)"
        state: >
          {{ state_attr('sensor.althermasensors', '3way valve(On:DHW_Off:Space)') }}
      - name: "Space H Operation output" 
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'Space H Operation output') }}

      - name: "Booster Heater" 
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'BSH') }}

      - name: "BUH Step1"
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'BUH Step1') }}
      - name: "BUH Step2"
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'BUH Step2') }}
      - name: "DWH Operation" 
        device_class: power
        state: >
          {{ state_attr('water_heater.domestic_hot_water_tank', 'operation_mode') }}

```
Those are then under "template:" section.


BTW, can you help me understand your equation?
> value_template: "{{ ( state_attr('sensor.althermasensors','INV Primärstrom (A)')  | float * 0.233 * 3 ) | round(3) }}"

What's this 0.233 and * 3 ? And how does it translate to kW?
