### DISCUSSION TITLE
[Rotex HPSU 508] Help with thermostat relay connection

### DISCUSSION THREAD

**Discussion by philipgo** [raomin/ESPAltherma#460] [General]
Hello,

I have a Rotex HPSU 508 Compact which I monitor with ESPAltherma. Now I would like to connect a thermostat relay but have some questions.

This is the current situation with bridge in place, no room thermostat:
![grafik](https://github.com/user-attachments/assets/f065a330-8d70-49da-9402-36b70251a6a9)

This is what the manual says about connecting a room thermostat:
![grafik](https://github.com/user-attachments/assets/efc631d7-e3a6-4803-b304-9adab3ca9386)

I would like to connect one/two? relays to emulate the function of the Rotex "RKRTW" room thermostat.

Questions:
- How can I define a second ("cooling") thermostat relay in ESPAltherma? As far as I understand, the feature is not yet implemented
- If I work with only one relay for heating, how can I activate cooling in summer?
- What do I do with the existing bridge between RT N and RT C if I only use one relay for heating?

Thank you!

**Comment by philipgo** [comment]
I now built a second device using an M5Stack Stamp C3U and two M5 Mini 3A Relay Units (U023) and programmed it using ESPHome. For me this has the advantage that I can connect the heating to "normally closed" and cooling to "normally open" so that if the device fails, heating will be activated. I also implemented a logic that prevents that both switches are activated at the same time.

Would love to see such a solution integrated in ESPAltherma.

In case anyone is also looking for a solution, this is the ESPHome Code I used:

```
esphome:
  name: esp32-c3u-thermostat-rotex
  friendly_name: esp32-c3u-thermostat-rotex

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xyz"

ota:
  - platform: esphome
    password: "xyz2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    name: "Relais 1: Heizanforderung RT (NC)"
    pin: GPIO1
    id: heizanforderung
    inverted: True
    on_turn_on: 
      then:
        - switch.turn_off: kuehlanforderung
  - platform: gpio
    name: "Relais 2: Kühl-Anforderung RT (NO)"
    pin: GPIO19
    inverted: False
    id: kuehlanforderung
    on_turn_on: 
      then:
        - switch.turn_off: heizanforderung
```
