### ISSUE TITLE
Home assistant sensors not available

### ISSUE THREAD

**Issue by OnktheMonk** [raomin/ESPAltherma#194]
I cannot get the sensor info available in HA I see the attributes and added the example code in configuration.yaml 
I can add them in cards but they display no info. Also did a restart.

**Comment by tarmor1** [comment]
Maybe could you share some example from configuration.yaml and print screen on how they display in cards?

**Comment by OnktheMonk** [comment]
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

cover:
  - platform: group
    name: Screens
    entities:
      - cover.badkamer_2
      - cover.bureau_2
      - cover.kinderkamer_2
      - cover.slaapkamer_2
      - cover.woonkamer_raam_2
      - cover.woonkamer_schuifraam_2

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.88.238/webcam/?action=snapshot
    mjpeg_url: http://192.168.88.238/webcam/?action=stream

notify:
  - name: hass agent Desktop Hendrick
    platform: hass_agent_notifier
    resource: http://192.168.88.30:5115/notify
  - name: "Mail Riccardo"
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: xxx@gmail.com
    encryption: starttls
    username: xxx@gmail.com
    password: !secret gmailHendrick
    recipient:
      - yyy@hotmail.com
    sender_name: "Hendrick"

sensor:
  - platform: template
    sensors:
      espaltherma_operation:
        friendly_name: "Operation mode"
        value_template: ""
      espaltherma_iuoperation:
        friendly_name: "Indoor Operation mode"
        value_template: ""
      espaltherma_dhw:
        friendly_name: "DHW Temp"
        value_template: ""
        unit_of_measurement: '°C'

#ads:
#  device: 5.32.252.106.1.1
#  port: 851
```

![Voorbeeld ESPaltherma](https://user-images.githubusercontent.com/97784494/204584883-38547f2b-cd20-4cc7-8b6e-9266e1d196ee.png)

If you need any other info. Please let me know.

**Comment by tarmor1** [comment]
Hi!
You defenitely need `value_template` to be populated. https://www.home-assistant.io/integrations/template#value_template
This is how I have the DHW tank temp (it's in HA terms "legacy template"), but works still. Anyway, you definitely need to have it set.
```
      dwh_water:
        friendly_name: "DHW tank temp. (R5T)"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.althermasensors', 'DHW tank temp. (R5T)') }}"

```
Try your value template out in Home Assistant Developer Tools > Templates:
![image](https://user-images.githubusercontent.com/106139715/204594229-24a2e36d-8ef2-4336-80d7-f433d10bcf6d.png)
.. and you can observe the actual value (43C in right side taken from the Attribute set by espaltherma)

**Comment by OnktheMonk** [comment]
That was the issue! Works now. Thank you for the info!

**Comment by AbeltjeNL** [comment]
@OnktheMonk, how did you manage to get the energy info into HA? Which unit model do you have and what config file do you use? I can't seem to read this info from my Altherma.

**Comment by OnktheMonk** [comment]
Yeah I get the info. But I have some issue with connectivity, I guess bad Dupont connectors. I orded a correct connector for the pcb and I'm waiting for them to arrive. Then I'll continue this project. Now I lose connection every half hour.

I have the EHVX08S23EJ6V.

**Comment by AbeltjeNL** [comment]
> Yeah I get the info. But I have some issue with connectivity, I guess bad Dupont connectors. I orded a correct connector for the pcb and I'm waiting for them to arrive. Then I'll continue this project. Now I lose connection every half hour.
> 
> 
> 
> I have the EHVX08S23EJ6V. 

Alright, but which /include/dev/file.h do you use?

**Comment by OnktheMonk** [comment]
I used this one: #include "def/ALTHERMA(LT_DA_04-08KW).h"

**Comment by AbeltjeNL** [comment]
> I used this one: #include "def/ALTHERMA(LT_DA_04-08KW).h"

Alright, thank you. Can you tell me how you managed to read the or make the energy sensors in HA? I can't seem to wrap my head around it. Are you using the COP calculation?

**Comment by OnktheMonk** [comment]
Not yet but I parked the project because of the connection loses until I get the right connectors. 

Here you can find a very good explanation (in Dutch) to get the info. But I guess that wont be an issue. 

https://gathering.tweakers.net/forum/list_message/73682572#73682572

**Comment by AbeltjeNL** [comment]
Dankjewel! 😁

**Comment by swalsh11** [comment]
I have a similar Issue,  all of the data comes through in MQTT, 
![image](https://user-images.githubusercontent.com/66870309/219975055-7985638e-2b6b-4622-9293-1a6df9a2e0ab.png)
however  when I set: 

```
      dwh_water:
        friendly_name: "DHW tank temp. (R5T)"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.althermasensors', 'DHW temperature(R5T)') }}"
        

```
it returns ""None"
![image](https://user-images.githubusercontent.com/66870309/219975212-60557da9-cc5d-4da2-9284-1828bcadc395.png)

This happens with all the entities, any help appreciated.  
        `

**Comment by tarmor1** [comment]
Hi!

> ```
>         value_template: "{{ state_attr('sensor.althermasensors', 'DHW temperature(R5T)') }}"
> ```
Are you sure your MQTT main element is `sensor.althermasensors`?
You get None if either attribute or main element is misspelled...


And btw, I recommend moving to the non-deprecated notion of sensors. This is how I have it. Using this you get as well HA Statistics and some other nifty stuff, eg getting icons according to device classes.
```
template:
  - sensor:
      - name: "LW setpoint (main)"
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: >
          {{ state_attr('sensor.althermasensors', 'LW setpoint (main)') }}

```

(And the binary states eg Booster heater, BUH heaters etc define as `binary_sensor` under `template`):
```
  - binary_sensor:
      - name: "Defrost Operation"
        device_class: power
        state: >
          {{ state_attr('sensor.althermasensors', 'Defrost Operation') }}
```

**Comment by swalsh11** [comment]
Thanks, I has the name incorrect somehow it was :
 sensor.altalthermaermasensors 
![image](https://user-images.githubusercontent.com/66870309/220122144-1d8ee45c-025d-40fc-aae6-59c2af4298cb.png)

This Code Works:

```
template:
  - sensor:
      - name: "LW setpoint (main)"
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: >
          {{ state_attr('sensor.altalthermaermasensors', 'LW setpoint (main)') }}
          

```
