### ISSUE TITLE
ESPAltherma not compatible with HomeAssitant 2022.12+

### ISSUE THREAD

**Issue by nicolasvila** [raomin/ESPAltherma#205]
ESPAltherma publishes 2 devices : 

- switch.altherma
- sensor.althermasensors

With latest update of HomeAssistant (2022.12) it is not allowed to declare MQTT entities as switch or sensor.
They have to be declared on the "mqtt" integration instead. The code has to be changed, in mqtt.h accordingly
This change in HomeAssistant was introduced few months ago, as you can see on this thread: https://community.home-assistant.io/t/mqtt-breaking-changes-rc-2022-6/426714/7

**Comment by tarmor1** [comment]
I have been running 2022.12 without issues with the following (although legacy, to my understanding) config since spring '22:
```
sensor:
  - platform: template
    sensors:
      watt:
        friendly_name: "Power Consumption"
        unit_of_measurement: 'kW'
        device_class: power
        value_template: "{{((state_attr('sensor.althermasensors','INV primary current (A)') | float * 235)/1000) | round(2)}}"
      outside_temp:
        friendly_name: "Outdoor air temp.(R1T)"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('sensor.althermasensors', 'Outdoor air temp.(R1T)') }}"
[..............]
```
