### ISSUE TITLE
ESPAltherma Dashboard Card

### ISSUE THREAD

**Issue by holger1982** [raomin/ESPAltherma#429]
Hallo!

Erstmal vielen Dank für die tolle Integration! Ich bin kein Programmierer und noch ziemlich neu bei HA. Ich habe soweit alles zum laufen bekommen aber was ich absolut nicht hinbekomme, ist diese schöne Übersicht von dem System wo man sich die ganzen Werte anzeigen lassen kann.
Ich hoffe, dass mir das hier Jemand irgendwie erklären kann? Danke!

**Comment by LaurensBot** [comment]
If you wrote it in English it would have helped people that don't speak German (more people understand English than German).

Here is my dashboard, nothing fancy and there is plenty of room for improvement:
```
  - title: Altherma Dashboard
    icon: mdi:thermometer
    cards:
      - type: entities
        entities:
          - entity: sensor.altherma_operation_mode
            name: Operation Mode
          - entity: sensor.altherma_3way_valve
            name: 3-way Valve (On:Hot Water Off:Space)
          - entity: sensor.altherma_space_heating_operation_on_off
            name: Space Heating Operation ON/OFF
          - entity: sensor.whole_house_power
        title: General Operation
        show_header_toggle: false
      - type: gauge
        entity: sensor.altherma_flow_sensor
        name: Flow Sensor
        min: 0
        max: 30
        severity:
          green: 10
          yellow: 20
          red: 30
        unit: l/min
        needle: true
      - type: gauge
        entity: sensor.altherma_hot_water_tank_temp
        name: Hot Water
        min: 0
        max: 60
        severity:
          green: 43
          yellow: 50
          red: 55
        unit: °C
        needle: true
      - type: gauge
        entity: sensor.altherma_leaving_water_setpoint
        name: Leaving Water Target
        min: 0
        severity:
          green: 20
          yellow: 28
          red: 34
        unit: °C
        needle: true
        max: 40
      - type: gauge
        entity: sensor.altherma_leaving_water_temp_before_buh
        name: Leaving Water
        min: 0
        max: 60
        unit: °C
        needle: true
        severity:
          green: 20
          yellow: 40
          red: 55
      - type: gauge
        entity: sensor.altherma_outdoor_air_temp
        name: Outdoor Air Temp
        min: -10
        max: 40
        severity:
          green: 10
          yellow: 30
          red: 35
        unit: °C
        needle: true
      - type: gauge
        entity: sensor.altherma_hot_water_setpoint
        name: Hot Water Target
        min: 0
        max: 60
        severity:
          green: 43
          yellow: 50
          red: 55
        unit: °C
        needle: true
      - type: gauge
        entity: sensor.altherma_target_delta_t_heating
        name: Delta T
        min: 0
        max: 20
        unit: °C
        severity:
          green: 4
          yellow: 7
          red: 10
        needle: true
      - type: gauge
        entity: sensor.altherma_inlet_water_temp
        name: Inlet Water
        min: 0
        max: 60
        unit: °C
        needle: false
      - type: history-graph
        entities:
          - sensor.altherma_hot_water_tank_temp
        name: Hot Water Tank Temperature History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_hot_water_setpoint
        name: Hot Water Target History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_leaving_water_setpoint
        name: Leaving Water Target History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_inlet_water_temp
        name: Inlet Water Temperature History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_outdoor_air_temp
        name: Outdoor Air Temperature History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_leaving_water_temp_before_buh
        name: Leaving Water Temperature before BUH History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_flow_sensor
        name: Flow Sensor (l/min) History
        hours_to_show: 24
        refresh_interval: 15
      - type: history-graph
        entities:
          - sensor.altherma_target_delta_t_heating
        name: Target Delta T Heating History
        hours_to_show: 24
        refresh_interval: 15
```

On your Dashboard click Edit (pencil icon), three dots and then raw configuration editor. Paste the config, click on Save and then the cross. Now you have a dashboard full with errors, edit each card and replace the entity with your own.
