### ISSUE TITLE
Home assistant missing celsius value

### ISSUE THREAD

**Issue by pengemetal** [raomin/ESPAltherma#6]
Hi,

Just one more question :) In HA is created sensors, but C is missing (and Amper too) everywhere. Is it possible heat pump dont give these values? It is important for grahps. I can see your sensors have these.
![image](https://user-images.githubusercontent.com/56131015/103762897-570ff480-5019-11eb-958b-a95893ab45c5.png)

**Comment by raomin** [comment]
Hi @pengemetal,

As explained in the Readme, you'll have to extract your Attributes as Entities using Template.
When you declare your Template you can specify a unit.
eg:
```yaml
  - platform: template
    sensors:
      espaltherma_dhw:
        friendly_name: "DHW Temp"
        value_template: "{{ state_attr('sensor.altherma','DHW tank temp. (R5T)') }}"
        unit_of_measurement: '°C'
```
Once you restart HA, your templated attributes will be available for your charts.
Happy dashboarding :)

--
If you like this project, please consider supporting it, [buy me a beer!](https://www.buymeacoffee.com/raomin)
